icons_format = "{icon}"

[theme]
theme = "native"
# [theme.overrides]
# idle_bg = "none"

[icons]
icons = "awesome6"

[[block]]
block = "pomodoro"
notify_cmd = "notify-send --urgency="critical" '{msg}'"

[[block]]
block = "custom"
command = "echo '\uf6ad' Stay Hungry Stay Foolish"
interval = 3600

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon disk $available.eng(w:2) "

[[block]]
block = "memory"
format = "$icon mem $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 5

# # [[block]]
# # block = "temperature"
# # collapsed = false
# # interval = 10
# # format = "{average} avg"
# # chip = "*-isa-*"
# # inputs = ["CPUTIN", "SYSTIN"]

# [[block]]
# block = "sound"
# format = "{output_description} {volume}"

# [[block]]
# block = "music"
# buttons = ["play", "next"]
# interface_name_exclude = [".*kdeconnect.*", "mpd"]
# on_collapsed_click = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m-%d %R') "

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
