[theme]
name = "native"
# name = "modern"
# [theme.overrides]
# idle_bg = "none"

[icons]
name = "awesome6"

# [[block]]
# block = "focused_window"
# max_width = 20
# show_marks = "visible"

[[block]]
block = "pomodoro"
task_len = 30
break_len = 5
notify_cmd = "$icon notify-send '{msg}'"
message = "Take a break!"
break_message = "Back to work!"
format = " $icon $pomodoro"

[[block]]
block = "custom"
command = "echo '\uf6ad' Stay Hungry Stay Foolish"
interval = 3600

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 5

# # [[block]]
# # block = "temperature"
# # collapsed = false
# # interval = 10
# # format = "{average} avg"
# # chip = "*-isa-*"
# # inputs = ["CPUTIN", "SYSTIN"]

# [[block]]
# block = "sound"
# format = "{output_description} {volume}"

# [[block]]
# block = "music"
# buttons = ["play", "next"]
# interface_name_exclude = [".*kdeconnect.*", "mpd"]
# on_collapsed_click = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 5
format = "%a %m-%d %R"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage"
